name: Docker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # No params

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push node
        uses: docker/build-push-action@v2
        with:
          context: docker/node
          push: true
          tags: ghcr.io/gear-tech/node:latest

      - name: Build and push node for workshop
        uses: docker/build-push-action@v2
        with:
          context: docker/node-workshop
          push: true
          tags: ghcr.io/gear-tech/node-workshop:latest

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: gear-tech/gear-js

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: website/backend/Dockerfile
          push: true
          tags: ghcr.io/gear-tech/backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: website/frontend/Dockerfile
          push: true
          tags: ghcr.io/gear-tech/frontend:latest
